
logging:
  level:
    org:
      springframework:
        cloud:
          config:
            client: trace
management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
